service:
  flask_redis-demo:
    build:
      context: ./
      dockerfile: dockerfile
    environment: 
      - REDIS_HOST=redis-server
    networks: 
      - demo-networks
    ports: 
      - "5000:5000"
    depends_on:
      - redis_server:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000"]
      interval: 30s
      retries: 3
      start_periods: 40s

  redis-server:
    image: redis:latest
    networks: 
      - demo-network

  networks:
    demo-network: